name:                regex-bird
version:             0.0.0
github:              "Zankoku-Okuno/regex-bird"
license:             BSD3
author:              "Okuno Zankoku"
maintainer:          "zankoku.okuno@gmail.com"
copyright:           "Okuno Zankoku"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Zankoku-Okuno/regex-bird#readme>

dependencies:
- attoparsec ==0.13.*
- base >=4.7 && <5
- containers >=0.5.8
- ListLike >=4 && <5
- text ==1.*
- symbol >=0.2

default-extensions:
- OverloadedStrings
- PatternSynonyms
- TupleSections
- ViewPatterns
- ConstraintKinds
- FlexibleInstances
- FlexibleContexts

library:
  source-dirs: src

tests:
  regex-bird-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-bird
